'use strict';
/*
 * Terminal Quest — web/Android bundler. Pure Node, zero dependencies.
 *
 * Wraps every game module in a tiny CommonJS loader and emits one bundle.js,
 * with browser shims for the three Node builtins the renderer touches:
 *   fs        -> localStorage-backed (saves + history persist in the WebView)
 *   path      -> join/normalize only
 *   electron  -> stub ipcRenderer (save dir = '/saves', window controls no-op)
 *
 * Output goes to webdist/ (open index.html in any browser to test) and is
 * mirrored into android-app/app/src/main/assets/www/ for the APK build.
 *
 *   node scripts/build-web.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'src');

// modules to bundle, keyed by their virtual path (used by the runtime loader)
const MODULES = [
  'src/engine/vfs.js',
  'src/engine/shell.js',
  'src/engine/script.js',
  'src/engine/man.js',
  'src/engine/commands.js',
  'src/engine/world.js',
  'src/engine/game.js',
  'src/game/levels.js',
  'src/game/exam.js',
  'src/game/drills.js',
  'src/term/ansi.js',
  'src/term/renderer.js'
];

const RUNTIME = `
// ---- Terminal Quest module runtime (browser) --------------------------------
(function () {
  'use strict';
  var MODS = {};   // virtual path -> factory(require, module, exports, __dirname)
  var CACHE = {};

  function norm(p) {
    var parts = [];
    var segs = String(p).split('/');
    for (var i = 0; i < segs.length; i++) {
      var s = segs[i];
      if (s === '' || s === '.') continue;
      if (s === '..') parts.pop();
      else parts.push(s);
    }
    return parts.join('/');
  }

  // ---- Node builtin shims ----
  var LSKEY = 'tqfs:';
  var fsShim = {
    readFileSync: function (p) {
      var v = window.localStorage.getItem(LSKEY + norm(p));
      if (v === null) { var e = new Error('ENOENT: no such file: ' + p); e.code = 'ENOENT'; throw e; }
      return v;
    },
    writeFileSync: function (p, data) { window.localStorage.setItem(LSKEY + norm(p), String(data)); },
    mkdirSync: function () {},
    rmSync: function (p) { window.localStorage.removeItem(LSKEY + norm(p)); },
    existsSync: function (p) { return window.localStorage.getItem(LSKEY + norm(p)) !== null; }
  };
  var pathShim = {
    join: function () { return Array.prototype.slice.call(arguments).join('/'); },
    normalize: norm
  };
  var electronShim = {
    ipcRenderer: {
      sendSync: function (ch) { return ch === 'tq:get-save-dir' ? '/saves' : null; },
      send: function () {},
      on: function () {}
    }
  };
  var BUILTINS = { fs: fsShim, path: pathShim, electron: electronShim };

  function makeRequire(fromDir) {
    return function require(spec) {
      if (BUILTINS[spec]) return BUILTINS[spec];
      var p = spec.charAt(0) === '.' ? norm(fromDir + '/' + spec) : norm(spec);
      if (!MODS[p] && MODS[p + '.js']) p = p + '.js';
      if (!MODS[p]) throw new Error("Cannot find module '" + spec + "' (resolved: " + p + ')');
      if (CACHE[p]) return CACHE[p].exports;
      var module = { exports: {} };
      CACHE[p] = module;
      var dir = p.split('/').slice(0, -1).join('/');
      MODS[p](makeRequire(dir), module, module.exports, dir);
      return module.exports;
    };
  }

  window.__TQ_DEFINE = function (p, factory) { MODS[p] = factory; };
  window.__TQ_BOOT = function (entry) { return makeRequire('')(entry); };
})();
`;

function build() {
  let out = '/* Terminal Quest — generated by scripts/build-web.js. Do not edit. */\n';
  out += RUNTIME;
  for (const vpath of MODULES) {
    const abs = path.join(ROOT, vpath);
    const code = fs.readFileSync(abs, 'utf8');
    out += `\n// ==== ${vpath} ====\n`;
    out += `window.__TQ_DEFINE(${JSON.stringify(vpath)}, function (require, module, exports, __dirname) {\n`;
    out += code;
    out += `\n});\n`;
  }
  out += `\nwindow.__TQ_BOOT('src/term/renderer.js');\n`;
  return out;
}

function copy(src, dst) {
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.copyFileSync(src, dst);
}

const bundle = build();

const TARGETS = [
  path.join(ROOT, 'webdist'),
  path.join(ROOT, 'android-app', 'app', 'src', 'main', 'assets', 'www')
];

for (const dir of TARGETS) {
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'bundle.js'), bundle);
  copy(path.join(SRC, 'mobile', 'index.html'), path.join(dir, 'index.html'));
  copy(path.join(SRC, 'mobile', 'mobile.js'), path.join(dir, 'mobile.js'));
  copy(path.join(SRC, 'mobile', 'mobile.css'), path.join(dir, 'mobile.css'));
  copy(path.join(SRC, 'term', 'style.css'), path.join(dir, 'style.css'));
  console.log('wrote', path.relative(ROOT, dir), `(bundle.js ${Math.round(bundle.length / 1024)} KB)`);
}
